# Generated by Django 2.2.16 on 2023-05-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230510_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='napravlenie_podgotovki',
            field=models.IntegerField(default=0),
        ),
    ]
