# Generated by Django 2.2.16 on 2023-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_course_napravlenie_podgotovki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='napravlenie_podgotovki',
            field=models.CharField(max_length=128),
        ),
    ]
